default_install_hook_types: [commit-msg, pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files


  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.6.8"
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture



  - repo: local
    hooks:
      # cannot use the official hook because it does not use wemake
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true

      # cannot use the official hook because it runs in isolated environment
      - id: mypy
        name: mypy
        entry: mypy --install-types --non-interactive .
        pass_filenames: false
        language: system
        types: [python]
