# Основной управляющий файл, задает основные параметры для обработки данных методом SWI
preprocessing:
  ffid_start: 0
  ffid_stop: 0
  ffid_increment: 0
  path4ffid_file:
  num_sources_on_cpu: 1

  data_dir: C:\Users\YablokovAV\PycharmProjects\SWI\data\data_2d_das
  type_data: 2d
  offset_min: 10
  offset_max: 130
  qc_preprocessing: True

  parameters_3d:
    sort_3d_order: csp
    num_sectors: 10
    bin_size_x: 50
    bin_size_y: 50

spectral:
  spectral_method: sfk
  fmin: 0
  fmax: 25
  vmin: 1
  vmax: 1200
  extract_dc_method: dbscan
  path4dc_limits: C:\Users\YablokovAV\PycharmProjects\SWI\configs\das\dc_limits.csv
  qc_spectral: True

  advanced:
    desired_nt: 1000
    desired_nx: 1000
    smooth_data: True
    width: 2
    peak_fraction: 0.5
    cutoff_fraction: 0.4
    dc_error_thr: 0.3

inversion:
  inversion_method: occam
  niter: 50
  max_num_modes: 3
  wavetype: rayleigh
  veltype: phase
  vp_model: vp2vs
  lock_vp: False
  path4vp_model: C:\Users\YablokovAV\PycharmProjects\SWI\configs\das\vp_model.csv
  qc_inversion: True

  global_search:
    test_count: 2
    path4vs_limits:
    xi: 1.5
    get_num_layers: every

  local_search:
    nlay: 25

postprocessing:
  max_depth: 50
  d_x: 1
  d_y: 1
  d_z: 1
  smooth_factor: 1
  remove_outliers_smoothing: True
  vmin_in_model: 200
  vmax_in_model: 800
  save_segy: False
  error_thr: 0.2

  parameters_2d:
    interp_dim: 1d

  parameters_3d:
    num_xslices_3d: 3
    num_yslices_3d: 3